### ISSUE TITLE
Use in Glide

### ISSUE THREAD

**Issue by tellfa** [hayribakici/imageprogressbar#1]
Can we use this library in Glide image library? 
How can use this in Glide? 

Thanks for this awesome library ❤️

**Comment by hayribakici** [comment]
Hi,

thank you very much! 
I honestly never heard of Glide before. But since it is like Picasso, I guess that you let glide load your image into the `ProgressImageView`, set your preferred Indicator and call `setProgress()` to do progression.

I haven't tried it, though.
cheers

**Comment by hayribakici** [comment]
Hi @tellfa !
I released a new version, which enables you to load images from picasso or from glide. 
The images can be from a remote server or on your disk.
I also added a gradle support, so you don't have to download the aar anymore.

Again, thank you for using this library!
cheers

**Comment by tellfa** [comment]
Thanks my dear friend ❤️
